
package com.bt.ws.weather.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidCityException", targetNamespace = "http://service.weather.ws.bt.com/")
public class InvalidCityException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidCityException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidCityException_Exception(String message, InvalidCityException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidCityException_Exception(String message, InvalidCityException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bt.ws.weather.service.InvalidCityException
     */
    public InvalidCityException getFaultInfo() {
        return faultInfo;
    }

}
