
package com.bt.ws.weather.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bt.ws.weather.WeatherReport;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherService", targetNamespace = "http://service.weather.ws.bt.com/")
@XmlSeeAlso({
    com.bt.ws.weather.ObjectFactory.class,
    com.bt.ws.weather.service.ObjectFactory.class
})
public interface WeatherService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.bt.ws.weather.WeatherReport
     * @throws InvalidCityException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeather", targetNamespace = "http://service.weather.ws.bt.com/", className = "com.bt.ws.weather.service.GetWeather")
    @ResponseWrapper(localName = "getWeatherResponse", targetNamespace = "http://service.weather.ws.bt.com/", className = "com.bt.ws.weather.service.GetWeatherResponse")
    @Action(input = "http://service.weather.ws.bt.com/WeatherService/getWeatherRequest", output = "http://service.weather.ws.bt.com/WeatherService/getWeatherResponse", fault = {
        @FaultAction(className = InvalidCityException_Exception.class, value = "http://service.weather.ws.bt.com/WeatherService/getWeather/Fault/InvalidCityException")
    })
    public WeatherReport getWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1)
        throws InvalidCityException_Exception
    ;

}
